name: Lomy Dome
favicon: null
layout_spectrum: 0.48634
typography_spectrum: 0.09848
title: Loy Dome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01010b'
    - '#32497b'
    - '#a06498'
    - '#ffffff'
    - '#f41635'
  brandStrength: 0.8125
  lightness: 0.6992783492896706
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
